### ISSUE TITLE
API V2

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#1209]
# Work
## TODO
- [ ] support async components
- [ ] adding a group | story | item at runtime should re-render hierarchy
- [x] support groups
- [x] support stateful functional components
- [x] create new api for getting complete hierarchy
- [x] create new api for getting sub hierarchy
- [x] create new api for subscribing to hierarchy changes
- [x] create new api for adding stories separating the real story from any decorators, connectors/options for addons.
- [x] more covfefe
- [x] create UI for navigating groups | stories | items
- [x] choose a good name for 'group' and 'item' 

## DONE
- [x] Write todo list

# Choices made
-none so far-

# Use cases
-I will put them in different comments for link-ability-

**Comment by ndelangen** [comment]
## Auto update UI after async story addition
```js
// This should just update UI automatically
import('../App').then(({ default: App }) =>
  storiesOf('App', module).add('with text', () => <App />)
);
```

**Comment by wcastand** [comment]
a quick tentative to resume the conversation on slack about the addon API, feel free to add more

#1212

**Comment by tmeasday** [comment]
@ndelangen I've looked into the auto update thing; If you want to make a separate issue I'm happy to take a crack at it.

**Comment by wcastand** [comment]
It would be cool to handle auto load for stories. going into the .config to add every story is tedious and can be avoided i think. Maybe we can specify on the config which folder needs to be loader or by allowing to put a pattern file matching :)

Something like jest could be nice too. A "dev-watch" mode that allow you to only see the modified story to render/iterate more quickly during development.

**Comment by tmeasday** [comment]
> It would be cool to handle auto load for stories

At the least I think we change the default setup to load `*.story.js` or the like.

**Comment by PhilDore11** [comment]
Any news on adding support for async components?

**Comment by blemaire** [comment]
@wcastand 

> It would be cool to handle auto load for stories. going into the .config to add every story is tedious and can be avoided i think. Maybe we can specify on the config which folder needs to be loader or by allowing to put a pattern file matching :)
> 
> Something like jest could be nice too. A "dev-watch" mode that allow you to only see the modified story to render/iterate more quickly during development.

Isn't this already supported using `require.context` ?
