### ISSUE TITLE
Community outreach to upgrade addons to 7.0

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#20529]
Storybook 7 (SB7) contains 2.5 years worth of breaking change and community addons need to be updated for SB7 compatibility. (All core addons have already been updated and issues mitigated via automigrations.)

To support developers as they migrate their addons to Storybook 7, we've created [an addon migration guide](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040) that outlines how to make your addons Storybook 7 compatible. We're keeping up-to-date records of the addons that are and aren't compatible with Storybook 7 and you can explore many of these in the lists below.

### Most popular community addons by npm downloads:

- [x] @storybook/addon-knobs (conversation started [here](https://github.com/storybookjs/addon-knobs/issues/47)) - [open PR](https://github.com/storybookjs/addon-knobs/pull/48)
- [x] chromatic
- [x] storybook-addon-designs (Supports Storybook 7 in a new package called `@storybook/addon-designs` - issue [here](https://github.com/storybookjs/addon-designs/issues/191))
- [ ] ~@storybook/addon-postcss (conversation started [here](https://github.com/storybookjs/addon-postcss/issues/44))~ Haven't been maintained in 2 years, and is fully superseded by `@storybook/addon-styling`. @Integrayshaun will release a version with a message telling users to migrate to `@storybook/addon-styling`.
- [x] msw-storybook-addon (conversation started [here](https://github.com/mswjs/msw-storybook-addon/issues/95))
- [x] @storybook/testing-react (conversation started [here](https://github.com/storybookjs/testing-react/issues/135))
- [ ] ~~storybook-addon-next-router~~ (checking this one off the list as the repository was archived as of 07/01/2023) 
- [ ] ~~storybook-addon-outline~~ (deprecated in favor of @storybook/addon-outline)
- [ ] ~~@storybook/addon-info~~ (checking this one of the list as there's been no movement in the past 2 years and he's not actively maintained anymore as it's superseded by the Docs addon)
- [x] @storybook/test-runner (conversation started [here](https://github.com/storybookjs/test-runner/issues/255))
- [ ] storybook-addon-next (ongoing discussion [here](https://github.com/RyanClementsHax/storybook-addon-next/discussions/160#discussioncomment-4497878) but deprecated in favor of [@storybook/nextjs](https://storybook.js.org/recipes/next))
- [x] ~~storybook-docs-toc~~ (conversation started [here](https://github.com/frassinier/storybook-docs-toc/issues/26)) (Archived as 1/08/2023 as Storybook now provides a table of contents as part of the 7.1 release)
- [ ] @storybook/addon-google-analytics (initial conversation started [here] (https://github.com/storybookjs/storybook/issues/20366) and issue raised [here](https://github.com/storybookjs/addon-google-analytics/issues/4) to address the changes) - [open PR](https://github.com/storybookjs/addon-google-analytics/pull/6)
- [x]  storybook-addon-pseudo-states (conversation started [here](https://github.com/chromaui/storybook-addon-pseudo-states/issues/55))
- [x] storybook-dark-mode (PR open [here](https://github.com/hipstersmoothie/storybook-dark-mode/pull/224))
- [ ] storybook-addon-gatsby (conversation started [here](https://github.com/prismicio-community/storybook-addon-gatsby/issues/10))
- [x] @etchteam/storybook-addon-css-variables-theme (conversation started [here](https://github.com/etchteam/storybook-addon-css-variables-theme/issues/38))
- [X] storybook-addon-angular-router (answered via this [issue](https://github.com/Jakob-em/storybook-addon-angular-router/issues/18))
- [ ] @storybook/addon-cssresources (conversation started [here](https://github.com/storybookjs/addon-cssresources/issues/7))
- [ ] ~~@storybook/addon-ie11~~ (Storybook 7 will not support IE11, checking this one of the list)
- [x] storybook-addon-grid (conversation started [here](https://github.com/maraisr/storybook-addon-grid/issues/16#issue-1528004318))
- [ ] storybook-multilevel-sort (conversation started [here](https://github.com/prantlf/storybook-multilevel-sort/issues/8))
- [x] storybook-addon-i18next (conversation started [here](https://github.com/stevensacks/storybook-react-i18next/issues/16), PR [here](https://github.com/stevensacks/storybook-react-i18next/pull/17))
- [X] storybook-source-link (conversation started [here](https://github.com/Sirrine-Jonathan/storybook-source-link/issues/5))
- [ ] ~babel-plugin-storybook-csf-title~ (conversation started [here](https://github.com/atlassian-labs/babel-plugin-storybook-csf-title/issues/24), looks like this is more or less superseded by the autotitle feature)
- [ ] @urql/storybook-addon (conversation started [here](https://github.com/urql-graphql/urql/discussions/2943))
- [X] storybook-addon-apollo-client (conversation started [here](https://github.com/lifeiscontent/storybook-addon-apollo-client/issues/89))
- [X] storybook-addon-intl (conversation started [here](https://github.com/truffls/storybook-addon-intl/issues/113))
- [X] storybook-addon-mock (already supporting Storybook 7 per this [comment](https://github.com/nutboltu/storybook-addon-mock/issues/148#issuecomment-1501042345))
- [X] @chakra-ui/storybook-addon (conversation started [here](https://github.com/chakra-ui/chakra-ui/issues/7402))
- [X] storybook-mobile-addon (conversation started [here](https://github.com/stevensacks/storybook-mobile-addon/issues/1))
- [x] @storybook/addon-queryparams (conversation started [here](https://github.com/storybookjs/addon-queryparams/issues/5))

#### I'm maintaining an addon. How do I make it compatible with Storybook 7?

We highly recommend consulting [our abridged addon migration guide](https://storybook.js.org/docs/react/addons/addon-migration-guide). If you have any questions or encounter any issues, please reach out to Storybook maintainers in the #addons channel in the [Storybook Discord community](https://discord.gg/storybook).

#### What do I do if an addon I'm using is incompatible with Storybook 7 but isn't on this list?

To share incompatibility errors, please open an issue on the repo of the relevant addon, asking the author to add Storybook 7 compatibility, and share this page with them for reference.

It's also really useful for us to know which addons aren't yet compatible, so please consider adding a comment here, especially if the addon is popular and causes a critical failure.

Finally, if you have the resources, please consider helping migrate that addon yourself!

**Comment by jonniebigodes** [comment]
@shilman If you don't mind, I'm going to assign myself to this as I've already started conversations with various maintainers. I'll keep updating the issue as feedback keeps rolling in. Sounds good?

**Comment by shilman** [comment]
Here's another one for the list @jonniebigodes 

https://www.npmjs.com/package/storybook-addon-mock

**Comment by jonniebigodes** [comment]
@shilman, thanks for the reminder. I'm updating the list with this one, and there's already a discussion about it.

**Comment by shilman** [comment]
One more `@chakra-ui/storybook-addon` 😉

**Comment by shilman** [comment]
Another https://storybook.js.org/addons/storybook-addon-pseudo-states

**Comment by shilman** [comment]
A few more errors from @yannbf QA:

#### storybook-addon-designs
```
[Storybook] One of your manager-entries failed: http://localhost:6006/sb-addons/designs-9/register-bundle.mjs TypeError: Ae.register is not a function
at Rt (register-bundle.mjs:735:2317)
at register-bundle.mjs:735:2750
```

#### storybook-addon-mobile
```
[Storybook] One of your manager-entries failed: http://localhost:6006/sb-addons/storybook-mobile-10/register-bundle.mjs ReferenceError: regeneratorRuntime is not defined
at register-bundle.mjs:2:11869
```

**Comment by jonniebigodes** [comment]
@shilman and @yannbf, regarding `storybook-addon-mobile`, which one are you using? If it's this [one](https://github.com/aholachek/storybook-mobile) it's pretty much abandoned. However, there's a fork [here](https://github.com/stevensacks/storybook-mobile-addon) and already a discussion happening which I'm going to follow up on.

**Comment by swrobel** [comment]
[@react-theming/storybook-addon](https://storybook.js.org/addons/@react-theming/storybook-addon) is referenced in [a recent blog post](https://storybook.js.org/blog/material-ui-in-storybook/) (as well as others) but it isn't compatible

**Comment by shilman** [comment]
@Integrayshaun can you please help with theming issues?

**Comment by ndelangen** [comment]
I've written a section in the `MIGRATION.md`-file about how addon-creators and addon-consumers can improve support for Storybook 7.0:

https://github.com/storybookjs/storybook/pull/21857

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.1 containing PR #21863 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by Integrayshaun** [comment]
> @Integrayshaun can you please help with this theming issue & provide guidance for best practices in 7.0? ☝

Absolutely! I need to remove those addons from the recipe

**Comment by nutboltu** [comment]
@jonniebigodes just a head's up  [storybook-addon-mock](https://github.com/nutboltu/storybook-addon-mock/issues/148#issuecomment-1501042345) has released new version which supports storybook v7.

**Comment by andrehil** [comment]
Can you add this one to the list? 😄 
https://github.com/ccpu/storybook-addon-playwright

**Comment by jonniebigodes** [comment]
@andrehil thanks for the suggestion, we appreciate it, but cases such as the one you mentioned (i.e., archived repositories) will not feature here, for consistency's sake.

**Comment by taozhou-glean** [comment]
`@storybook/addon-queryparams` seems not on the list, but probably should too

**Comment by ldm-acn** [comment]
After the upgrade to version 7 I'm running the packages listed below and I'm getting an issue with `storybook-addon-react-router-v6`.

This is the conflict:
```
@storybook/components@"^6.4.0" from storybook-addon-react-router-v6@0.3.5
@storybook/components@"^7.0.0" from storybook-react-i18next@2.0.1
```

```
"@storybook/addon-actions": "^7.0.4",
"@storybook/addon-essentials": "^7.0.4",
"@storybook/addon-interactions": "^7.0.4",
"@storybook/addon-links": "^7.0.4",
"@storybook/builder-vite": "^7.0.4",
"@storybook/react": "^7.0.4",
"@storybook/testing-library": "^0.1.0",
"storybook-addon-react-router-v6": "^0.3.5",
"storybook-react-i18next": "^2.0.1",
```

**Comment by taozhou-glean** [comment]
> @taozhou-glean appreciate the follow-up, and to give you a bit more context, the `@storybook/addon-queryparams` has been outdated for quite some time, if not mistaken, since version 6.4 as we don't have a dedicated maintainer for that particular addon. If you're ok with it and you're interested in getting support for Storybook 7, we'd love to see that. In the meantime, I'll add it to the list.

Do we plan to deprecate it officially in the future ? I briefly checked the code there and it's such a small addon that everyone probably can easily make one themselves with a decorator ;) Anyway, I thought it's a good opportunity for myself to get a bit more familiar with storybook 7, so I have sent https://github.com/storybookjs/addon-queryparams/pull/6 to add the support of v7 for that addon ;)

**Comment by DonatienD** [comment]
`themeprovider-storybook` ([link](https://github.com/semoal/themeprovider-storybook)) could probably be added to the list too.

**Comment by adnandedhawala** [comment]
Is the `storybook-addon-codepen` addon incompatible with storybook version 7?

**Comment by Integrayshaun** [comment]
@adnandedhawala Not yet. The maintainer hasn't upgraded to 7.0 in their dependencies
https://github.com/elseloop/storybook-addon-codepen/blob/main/package.json

**Comment by Integrayshaun** [comment]
@DonatienD It looks like the maintainer hasn't updated this addon in 2 years.

If you're looking for ThemeProvider support, I'd recommend using [`@storybook/addon-styling`](https://storybook.js.org/addons/@storybook/addon-styling/)

**Comment by ldm-acn** [comment]
> @ldm-acn, thanks for reaching out to us and letting us know. I saw that you already reached out to the maintainer of that particular addon, and based on his response, he was planning on releasing a new version next Thursday. With that, I was wondering if you could follow up with us and let us know if the new release will work with 7.0 so that we can adjust the list above and add this as well.

storybook-addon-react-router-v6 is now at version 1.0.0 and compatible with Storybook 7

**Comment by volnei** [comment]
@whitespace/storybook-addon-html

**Comment by TylerAPfledderer** [comment]
@shilman `@chakra-ui/storybook-addon` is now waiting for release of its update!

**Comment by pedaars** [comment]
what about storybook-addon-themes https://storybook.js.org/addons/storybook-addon-themes

**Comment by Integrayshaun** [comment]
@pedaars have you tried [`@storybook/addon-themes`](https://storybook.js.org/addons/@storybook/addon-themes/)?

**Comment by pedaars** [comment]
> @storybook/addon-themes

any example of getting it to work with scss

**Comment by Integrayshaun** [comment]
@pedaars if your Storybook is built with Webpack, you can configure scss using [`@storybook/addon-styling-webpack`](https://storybook.js.org/addons/@storybook/addon-styling-webpack).

If you give me some more details about your Storybook, I can make a StackBlitz example for you to look at.

**Comment by maraisr** [comment]
@shilman `storybook-addon-grid@0.4` is now v7 compatible 🎉

**Comment by vksingh26** [comment]
Hey @shilman, is there any plan to upgrade/migrate `storybook-addon-preview` addons? We have upgraded storybook with V7/V8 and when we try to consume preview addon, it throws error as seen in the screenshot. 

<img width="852" alt="Screenshot 2024-04-16 at 19 03 05" src="https://github.com/storybookjs/storybook/assets/121873611/2d054898-1795-4611-a460-de441be41384">

<img width="1501" alt="Screenshot 2024-04-16 at 19 02 33" src="https://github.com/storybookjs/storybook/assets/20810592/1b6023df-6337-4fac-a557-797bdf54f4f2">

**Comment by jonniebigodes** [comment]
Closing this as we're currently on Storybook 9.

**Comment by FengXiLo** [comment]
How can I check the documentation for Storybook 7.x now? I see that the official documentation only supports viewing version 8 at a minimum, but my project is using Vue 2, so I need version 7.
