### ISSUE TITLE
[Tracking] Improved Storybook init Error Handling

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#22243]
Keeping track of the work regarding 

There are plenty of errors happening from `npx storybook init` which block users from installing Storybook. Here's a list of issues to investigate and improve upon:

```[tasklist]
### Tasks
- [ ] https://github.com/storybookjs/storybook/issues/22342
- [ ] https://github.com/storybookjs/storybook/issues/22570
- [ ] https://github.com/storybookjs/storybook/issues/22343
- [ ] https://github.com/storybookjs/storybook/issues/22345
- [ ] https://github.com/storybookjs/storybook/issues/22346
- [ ] https://github.com/storybookjs/storybook/issues/22348
- [ ] https://github.com/storybookjs/storybook/issues/22349
- [ ] https://github.com/storybookjs/storybook/issues/22350
- [ ] https://github.com/storybookjs/storybook/issues/22351
```
