### ISSUE TITLE
[Tracking] Release Tooling

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#22532]
Tracking progress for the implementation of https://github.com/storybookjs/storybook/discussions/22182

```[tasklist]
### Tasks
- [x] Bring back prototype repo to a pristine state without Changesets
- [x] Build `version` script that bumps versions everywhere https://github.com/storybookjs/monorepo-release-tooling-prototype/pull/17
- [ ] https://github.com/storybookjs/storybook/issues/22611
- [ ] https://github.com/storybookjs/storybook/issues/22601
- [ ] https://github.com/storybookjs/storybook/issues/22603
- [ ] https://github.com/storybookjs/storybook/issues/22604
- [ ] https://github.com/storybookjs/storybook/issues/22610
- [ ] https://github.com/storybookjs/storybook/issues/22605
- [ ] https://github.com/storybookjs/storybook/issues/22606
- [ ] https://github.com/storybookjs/storybook/issues/22607
- [ ] https://github.com/storybookjs/storybook/issues/22608
- [x] Create a video tour of the workflow from A-Z that clearly demonstrates how we work with it, to gather feedback on if we want to change the main workflow
- [ ] https://github.com/storybookjs/storybook/issues/22837
- [x] Change branches from "main-v2-release" and "next-v2-release" to "release/next" and "release/main"
- [ ] https://github.com/storybookjs/storybook/issues/22840
- [x] Fail release PR until all checks are complete
- [ ] https://github.com/storybookjs/storybook/issues/22609
- [x] Handle when `next` gets new changes while release is ongoing. Probably tag the versioning commit and not the merge one
```

```[tasklist]
### Migrating prototype to monorepo
- [x] Add scripts, dependencies and Actions and anything else necessary to the monorepo with a PR to `next`. #22959
- [x] Figure out what `handle-release-branches.yml` does
- [x] Add secrets and environments via the GH UI
- [x] Merge to next and hopefully see the "Version Packages" PR
- [x] Merge the "Version Packages" PR and hopefully trigger a new 7.1.0-alpha version release
- [x] Ensure monitoring, status page and scheduled CI still works with the branches
```
```[tasklist]
### Follow up tasks
- [ ] https://github.com/storybookjs/storybook/issues/23000
- [x] Changes to `CHANGELOG.md` will only happen on `main`, should be changed on `next` as well
- [x] Simplify PR list in description - remove 3 todos per PR
- [x] Add information to PR list about which PRs are also patching
- [x] Sort PRs by importance (to-be-released at the top)
- [ ] ~Remove all the deprecated bits that aren't necessary for releases anymore.~
- [x] Cherry picks can also fail with "empty commit" message if it has already been picked, in which case it shouldn't cause a "manual cherry pick needed" message
- [x] Change Release PR titles to "Release: <Type> [ID] <next-version>", eg: "Release: Prerelease beta 7.1.0-beta.0
```
