### ISSUE TITLE
[Tracking] Storybook Onboarding

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#22558]
This ticket is a tracking ticket for implementing the new Storybook Onboarding flow.

-----

```[tasklist]
### 1. Milestone - Prepare `@storybook/addon-onboarding`
- [ ] https://github.com/storybookjs/addon-onboarding/issues/15
```

```[tasklist]
### 2. Milestone - Minimum setup of `@storybook/addon-onboarding`
- [ ] https://github.com/storybookjs/addon-onboarding/issues/14
- [ ] https://github.com/storybookjs/addon-onboarding/issues/13
```

```[tasklist]
### 3. Milestone - Component development and library selection
- [ ] https://github.com/storybookjs/addon-onboarding/issues/12
- [ ] https://github.com/storybookjs/addon-onboarding/issues/11
- [ ] https://github.com/storybookjs/addon-onboarding/issues/8
- [ ] https://github.com/storybookjs/storybook/issues/22673
- [ ] https://github.com/storybookjs/storybook/issues/22675
- [ ] https://github.com/storybookjs/addon-onboarding/issues/9
- [ ] https://github.com/storybookjs/storybook/issues/22785
- [ ] https://github.com/storybookjs/storybook/issues/22786
- [ ] https://github.com/storybookjs/storybook/issues/22783
- [ ] https://github.com/storybookjs/addon-onboarding/issues/10
```

```[tasklist]
### 4. Milestone - Implement onboarding flow
- [ ] https://github.com/storybookjs/addon-onboarding/issues/16
- [ ] https://github.com/storybookjs/storybook/issues/22891
```

```[tasklist]
### 5. Milestone - Tracking
- [ ] https://github.com/storybookjs/addon-onboarding/issues/36
- [ ] https://github.com/storybookjs/addon-onboarding/issues/39
- [x] Add `onboarding_story_count` to project metadata
```

```[tasklist]
### 6. Milestone - Styling/polishing/cleanup
- [ ] https://github.com/storybookjs/addon-onboarding/issues/23
- [ ] https://github.com/storybookjs/addon-onboarding/issues/24
- [ ] https://github.com/storybookjs/addon-onboarding/issues/25
- [ ] https://github.com/storybookjs/addon-onboarding/issues/26
- [ ] https://github.com/storybookjs/addon-onboarding/issues/17
- [ ] https://github.com/storybookjs/addon-onboarding/issues/27
- [ ] https://github.com/storybookjs/addon-onboarding/issues/28
- [ ] https://github.com/storybookjs/addon-onboarding/issues/29
- [ ] https://github.com/storybookjs/addon-onboarding/issues/30
- [ ] https://github.com/storybookjs/addon-onboarding/issues/31
- [ ] https://github.com/storybookjs/addon-onboarding/issues/32
- [ ] https://github.com/storybookjs/storybook/issues/22977
- [ ] https://github.com/storybookjs/storybook/issues/22978
- [ ] https://github.com/storybookjs/storybook/issues/22980
```

```[tasklist]
### 7. Milestone - Connect Onboarding flow to Storybook's CLI
- [ ] https://github.com/storybookjs/storybook/issues/22870
- [ ] https://github.com/storybookjs/storybook/issues/22871
- [ ] https://github.com/storybookjs/storybook/issues/22872
- [ ] https://github.com/storybookjs/storybook/issues/22784
```

```[tasklist]
### 8. Milestone - QA
- [x] Test in Latest Safari
- [x] Test in latest Chrome
- [x] Test in latest Firefox
- [x] Test in latest Edge
- [x] Test in dark/light mode
- [x] Test responsiveness
- [x] Test all react-based frameworks once. Make sure the right code in the SyntaxHighlighter is shown (Javascript, Typescript and Next.js (Typescript/Javascript)
- [x] Make sure @storybook/addon-onboarding is not listed in addon catalog
```

```[tasklist]
### Design Tasks
- [x] Fix moving backgrop in the syntaxHighlighter
- [x] Change copy sentence to have the path underneath
- [x] Improve guided tour in dark mode
- [x] Fix Copy Button positioning
- [ ] Explore more inspiring ways to present features in the configure page
- [ ] https://github.com/storybookjs/addon-onboarding/issues/60
```

```[tasklist]
### 9. Rollout
- [x] Change the `@storybook/telemetry` dependency in `@storybook/addon-onboarding` to the version, which ships https://github.com/storybookjs/storybook/pull/22940 and test whether telemetry events are sent
- [x] Merge https://github.com/storybookjs/storybook/pull/22972 into next. Do NOT patch it back to `main`.
- [ ] [Optional] Announcement post on Discord. Talk with Joe about the timing and when to release the post. Ask explicitly for community feedback within the post
```
