### ISSUE TITLE
[Tracking] Changelog

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#23044]
### Background

Storybook currently has a mechanism to show changes for the latest version. It’s fairly minimal and shows a changelog. It doesn’t work on published Storybooks currently. In order to keep our users up to date, it would be good to update it with a monthly cadence and including news, articles, new addons, and more among the more basic changelog requirements. This will add value to Storybook, show the progress of the community, highlight addons, and showcase work done by community members.

### Solutions and plans

At a high level, the plan is to do the following:

1. Reframe the changelog as “What’s new?” that includes the changelog along with a roundup of all the project updates across the platform within the last month.
    1. Frame as “What’s new”
    2. Include updates from patch releases
    3. Include featured users or stories
    4. Include Chromatic updates
    5. Include link to sign up to Chromatic
2. Add tracking to whether the notifications have been read or not and adjust the UI once they have been read.
3. Build in ways to disable “What’s new?”. This is useful for folks who don’t want to see it for any number of reasons.
    1. Add an option to disable within the app saved in the browser’s local storage
    2. Add an option to disable via a config setting
    3. Disable it for published Storybooks
4. Build a mechanism to trigger the updates at a cadence of our choosing. We are initially going to start with a monthly cadence.

```[tasklist]
### Tasks
- [ ] https://github.com/chromaui/blog/pull/107
- [ ] https://github.com/storybookjs/dx-functions/pull/8
- [x] Extend notifications API according to design
- [x] Hook up "what's new" to the new API end point
- [x] Just use core event enums for now (and do the new type system for messages later)
- [x] Use the channel for "GET" request, and merge SUCCESS/ERROR messages
- [x] Remove or rename all stuff related to release notes
- [x] Implement green dot when what's new is unread, even when dismissed
- [x] Implement option in main.ts
- [x] Remove update notification (do cleaning later)
- [x] Remove changelog from about page (make it pretty later)
- [x] [beta] Make sure to not clash with onboarding
- [x] [beta] Implement disable button (using main.ts) and send telemetry events
- [x] [beta] Pretty minimal design for about Page including "Check for updates"
- [x] [beta] Remove all code related to notification checker
- [x] [before RC] ship with flag `whatsNewNotifications: true` by default
- [ ] [after 7.1] Improve type system of channel messages
- [ ] [after 7.1] Use a normal get request with trpc.io
```
