### ISSUE TITLE
[Tracking]: Indexer API

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#23457]
# Indexer API Tracking issue

RFC: https://github.com/storybookjs/storybook/discussions/23176

```[tasklist]
### 1. Indexer API
- [x] Add tests to existing indexer functionality
- [x] Implement changes to the indexer API and expose types
- [x] Migrate existing story indexers to new indexer API
- [ ] ~Remove old experimental indexer API~
- [x] Mark new API as experimental
```

```[tasklist]
### 2. Documentation
- [x] Document new indexer API (in collaboration with DX)
- [ ] ~Announce new indexer API, describing existing usages and potential future applications (in collaboration with DX)~ Postponed until docs indexers are available too
- [x] Write migrations notes from `storyIndexers` to `indexers`
- [x] Enable deprecations (warnings, `@deprecated` JSDocs) for `storyIndexers`
- [x] Deprecate `storiesOf`
- [x] Update the RFC to match the "final" API and decisions
```

```[tasklist]
### Follow-up tasks
- [x] Migrate [`addon-svelte-csf`](https://github.com/storybookjs/addon-svelte-csf) indexer to the new API -- potentially call for contribution?: https://github.com/storybookjs/addon-svelte-csf/issues/147
- [x] Reach out to maintainer for [`storybook-vue-addon`](https://github.com/tobiasdiez/storybook-vue-addon) to migrate existing indexer to use the new API: https://github.com/tobiasdiez/storybook-vue-addon/issues/87
```
