### ISSUE TITLE
[Tracking]: Improve "Storybook dev" error handling

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#23515]
### Describe the bug

Keeping track of the work regarding 

There are plenty of errors happening from when running `start-storybook` which users experience often. Here's a list of issues to investigate and improve upon:

```[tasklist]
### Tasks
- [ ] https://github.com/storybookjs/storybook/issues/24071
- [ ] https://github.com/storybookjs/storybook/issues/23601
- [ ] https://github.com/storybookjs/storybook/issues/23992
- [ ] https://github.com/storybookjs/storybook/issues/23945
- [ ] https://github.com/storybookjs/storybook/issues/23620
- [ ] https://github.com/storybookjs/storybook/issues/23928
- [ ] https://github.com/storybookjs/storybook/issues/23914
- [ ] https://github.com/storybookjs/storybook/issues/24006
```

```[tasklist]
### Followup Tasks
- [ ] https://github.com/storybookjs/storybook/issues/24026
- [x] https://github.com/storybookjs/storybook/issues/24035
- [ ] https://github.com/storybookjs/storybook/issues/24027
- [ ] https://github.com/storybookjs/storybook/issues/24030
```
