### ISSUE TITLE
[Tracking]: Storybook errors categorization 

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#23510]
By defining a categorization of errors, we can standardize how errors are defined in the Storybook codebase, making it easier to navigate, identify and to document them.

```[tasklist]
### Tasks
- [ ] https://github.com/storybookjs/storybook/issues/23511
- [ ] https://github.com/storybookjs/storybook/issues/23512
- [ ] https://github.com/storybookjs/storybook/issues/23513
```
