### ISSUE TITLE
[Tracking] Explicit Actions Args Mocking

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#23869]
Tracking work items to implement https://github.com/storybookjs/storybook/discussions/23649.

```[tasklist]
### Milestone 1: “New” `@storybook/test` package
- [ ] https://github.com/storybookjs/storybook/issues/23870
- [x] Release `@storybook/test` as a canary
```

```[tasklist]
### Milestone 2: Release `@storybook/test` officially
- [ ] https://github.com/storybookjs/storybook/issues/24210
- [ ] https://github.com/storybookjs/storybook/issues/23873
```

```[tasklist]
### Milestone 3: Deprecations
- [ ] https://github.com/storybookjs/storybook/issues/24135
- [ ] https://github.com/storybookjs/storybook/issues/24172
- [ ] https://github.com/storybookjs/storybook/issues/23871
- [ ] https://github.com/storybookjs/storybook/issues/24171
- [x] Release in 7.6-alpha (then subsequently 7.6.0)
```
```[tasklist]
### Nice to Have
- [ ] https://github.com/storybookjs/storybook/issues/23872
- [ ] https://github.com/storybookjs/storybook/issues/15012
- [ ] https://github.com/storybookjs/storybook/issues/21551
```

**Comment by vanessayuenn** [comment]
Closing this as it's done
