### ISSUE TITLE
[Tracking]: Mobile UI

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#24124]
# Tracking issue for new mobile UI

## Design
Storybook on mobile has not been worked on for a long time and a lot of patterns from desktop doesn’t work on mobile. The mobile storybook experience is becoming more important both for the web and React Native. With this project we have an opportunity to improve how people discover stories and use Storybook more to test their app on mobile.

https://github.com/storybookjs/storybook/assets/5678122/a37e962f-b33a-4472-8305-dd88ccd0a3b7

```[tasklist]
### Tasks
- [ ] https://github.com/storybookjs/storybook/issues/24215
- [ ] https://github.com/storybookjs/storybook/issues/24213
- [x] https://github.com/storybookjs/storybook/issues/24252
- [ ] https://github.com/storybookjs/storybook/issues/24216
- [ ] https://github.com/storybookjs/storybook/issues/24220
- [ ] https://github.com/storybookjs/storybook/issues/24221
- [ ] https://github.com/storybookjs/storybook/issues/24222
- [x] https://github.com/storybookjs/storybook/issues/24253
- [ ] https://github.com/storybookjs/storybook/issues/24255
- [ ] https://github.com/storybookjs/storybook/issues/24256
- [ ] https://github.com/storybookjs/storybook/issues/24254
- [ ] https://github.com/storybookjs/storybook/issues/24365
- [ ] https://github.com/storybookjs/storybook/issues/24257
- [ ] https://github.com/storybookjs/storybook/issues/24261
- [ ] https://github.com/storybookjs/storybook/issues/23723
- [ ] Check why the default size of the sidebar is different from what we have today.
- [ ] https://github.com/storybookjs/storybook/issues/24424
```

```[tasklist]
### Nice-to-haves
- [ ] Add drag handle to navigation drawer to close
- [ ] Add drag handle to addon panel to resize
```

```[tasklist]
### Ensure we don't break things
- [ ] Query parameters https://chromaticqa.slack.com/archives/C05M98X79U0/p1694592037758769
- [x] Notifications - Desktop
- [x] Notifications - Mobile
- [ ] Onboarding addon
- [x] Full screen toggle - Desktop
- [x] Full screen toggle - Mobile
- [x] Resize panels - Desktop
```
