### ISSUE TITLE
[Tracking]: Officially deprecate addon storyshots

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#24657]
### Describe the bug

This is a tracking issue for officially deprecating `@storybook/addon-storyshots`.

## Problem

Storyshots was replaced by the Test Runner over 1.5y ago but we are still supporting it via Github issues (12+ open, 300+ closed) & also via the feature flag storyStoreV7 disabled, which is a performance and maintenance problem for Storybook core.

Additionally, Storybook 8 will fully embrace storyStoreV7 and its [on-demand architecture](https://storybook.js.org/blog/storybook-on-demand-architecture/), meaning it will be the only option. Storyshots is incompatible with such architecture.

This project aims to provide a migration path for users who want to keep testing their stories successfully in Storybook 8, and hopefully get a better, more future proof experience.

## Solution

```[tasklist]
### Documentation
- [ ] https://github.com/storybookjs/storybook/pull/23863
- [ ] Storyshots <-> test-runner feature/support comparison table
- [ ] Recipe for storyshots to Vitest using `composeStories` and `import.meta.glob`
- [ ] Recipe for storyshots to Jest using `composeStories`
- [ ] Migration guide for storyshots to test-runner
- [ ] Deprecate `@storybook/addon-storyshots` on npm
- [ ] Communicate regarding the migration guide on GH issues that relate to addon-storyshots
```

```[tasklist]
### Core
- [ ] https://github.com/storybookjs/storybook/pull/24653
- [ ] https://github.com/storybookjs/storybook/pull/24438
```

**Comment by jonniebigodes** [comment]
@yannbf is anything missing here or we can close this one out? Let me know and we'll take it from there.
