### ISSUE TITLE
[TRACKING]: Support SWC for Webpack5 projects 

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#24725]
## Tasks

```[tasklist]
### Tasks
- [ ] https://github.com/storybookjs/storybook/issues/24763
- [ ] https://github.com/storybookjs/storybook/issues/24748
- [ ] https://github.com/storybookjs/storybook/issues/24750
- [ ] https://github.com/storybookjs/addon-coverage/issues/29
- [ ] https://github.com/storybookjs/storybook/issues/24827
- [ ] https://github.com/storybookjs/storybook/issues/24869
```
