### ISSUE TITLE
[Tracking]: Storybook 8 - Breaking Changes

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#25115]
This issue serves to monitor and document the non-backwards compatible changes that will be introduced in Storybook's major update to version 8. It provides a platform for the contributors to list the expected breaking changes, discuss their impact, propose migration strategies, and collaborate on the development and transition process.

```[tasklist]
### Features and Upgrades
- [ ] https://github.com/storybookjs/storybook/issues/25172
- [ ] https://github.com/storybookjs/storybook/issues/25174
- [ ] https://github.com/storybookjs/storybook/issues/25127
- [ ] https://github.com/storybookjs/storybook/issues/25182
- [ ] https://github.com/storybookjs/storybook/issues/25128
```

```[tasklist]
### Removals
- [x] https://github.com/storybookjs/storybook/issues/25185
- [ ] https://github.com/storybookjs/storybook/issues/25117
- [x] Drop Vue2 support
- [x] Drop Next.js < 13.5 support (https://github.com/storybookjs/storybook/pull/25104
- [x] Drop Angular 14 support (https://github.com/storybookjs/storybook/pull/25101)
- [ ] https://github.com/storybookjs/storybook/issues/25330
- [ ] https://github.com/storybookjs/storybook/issues/25358
- [ ] https://github.com/storybookjs/storybook/issues/25331
```

```[tasklist]
### Explicit Action args
- [x] Runtime error when action args generated from docgen are used in story rendering or the play function.
- [x] Remove the TS magic of making required action args optional
- [x] Make sure play function errors out when event handlers fail
- [x] Remove argTypesRegex from sb init
- [ ] https://github.com/storybookjs/storybook/issues/25583
```

**Comment by valentinpalkovic** [comment]
@shilman I guess we don't want to have any `@storybook/jest` references in 8.0. Should I add another task to replace `@storybook/jest` by `@storybook/test`? We are still using `@storybook/jest` in some stories and it is also added for the sandboxes.

**Comment by shilman** [comment]
@valentinpalkovic good call! 👍

**Comment by valentinpalkovic** [comment]
@shilman Let's drop Ember < 4.12 support since it is no longer maintained: https://emberjs.com/releases/lts/
WDYT?

**Comment by shilman** [comment]
@valentinpalkovic I'd rather not rock the boat on Ember until we have a path forward to work with the community. Let's discuss after 8.0 unless you feel strongly this needs to be dealt with now.
