### ISSUE TITLE
[Tracking]: Remove React peer dependencies from Docs addon

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#25179]
This is a tracking issue to track the work on removing `react` and `react-dom` as peer dependencies if `@storybook/addon-docs`.

The project was initially spiked in #24881.

```[tasklist]
### Milestone 1: Merge the spike PR: #24881
- [x] Fix the failing unit test
- [x] Add an E2E test that checks the output of an MDX file that lists the current React version
- [x] Test in all relevant project permutations
- [x] Fix Preact
```

```[tasklist]
### Milestone 2: Adjust DX
- [x] Add prompt-only automigration telling users that they might be able to remove `react` and `react-dom` from their dependencies now
- [x] Remove the `addReact` automigration
- [x] Stop adding `react` and `react-dom` dependencies on `init`
- [x] Add internal React 16 sandbox to test behavior of project-defined React version
```

```[tasklist]
### Milestone 3: Update Documentation
- [x] Don't say that React is necessary anymore (if we say that now)
- [x] Document that users can specify their own React version for docs/mdx if they need to
```

## Unknowns

As part of this project we need to answer and potentially resolve the following unknowns:

### How does MDX + React-based docs in a non-React project?

From the spike we already know that MDX works even in non-React projects without React.
But how will it work if users write their own React components to be imported in their MDX docs? Do they then need to add React as a dependency? Only at runtime, or also to satisfy type checkers? Is there anything we need to document here?

**Resolution**:

I haven't experienced any issues when trying this out in various projects using the canary release, without or without React.

### Can we test this in CI?

We can (and will) test the default behavior in React and non-React frameworks, that should both work in plain MDX and React-components-imported-to-MDX. However can we also test the functionality of users specifying their own React version? And if so, how?

This is further complicated by the fact that SB 8 will only support React 18, and thus "specifying your own React version" is currently only really valid for users that wants to use a canary version. Using React 16 will not be supported.

**Resolution**:

We will create an internal React 16 sandbox that tests if the project-defined React version is used. (this sandbox will also test that Storybook still supports React 16 in general)

### Should it be opt-outable?

We're doing something rather unusual to make all of this work, and there could be unknown unknowns that would make this break for users. Should we implement a feature flag that completely disables the whole `resolveReact` flow as an escape hatch for users experiencing problems?

**Resolution**:

We most likely can't make this opt-outable at all, so we won't try initially.

### Should we document the `resolvedReact` preset property?

This property should only be used internally in the docs addon, the React renderer and our common presets.
However it is technically possible for a user to set this manually, although the use case for it is rather slim.
We _know_ from the spike that this would be necessary for users in a non-React project that _also_ uses Yarn PnP and _also_ needs to manually specify a React version.

Documenting it would make it a public API with all the obligations that follows.

**Resolution**:

We won't document this, as the need and use case is extremely slim. Testing this in all permutations will shine a light on this. If user issues comes up we can describe workarounds in those issues directly.
