### ISSUE TITLE
Upgrade to MDX 3

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#25182]
## Breaking Changes

> The main breaking change is that Node.js 16 is now the minimum supported version. 
Across the ecosystem there were several small internal breaking changes. Everything’s released already. You can update all plugins now. If you ran into problems before, it should work now.
We also removed some infrequently used deprecated APIs. You’re likely fine but gloss over the [v3 migration guide](https://mdxjs.com/migrating/v3/) if you get errors.
Important to note when you use your lesser-known but powerful evaluate, run, or outputFormat: 'function-body' APIs, please pass the baseUrl option. That makes sure import.meta.url, import, and export work. You’ll get a runtime error when those features are used otherwise.

from https://mdxjs.com/blog/v3/

## Migration Guide

https://mdxjs.com/migrating/v3/

## Tasks

```[tasklist]
### Tasks
- [x] Update to MDX 3
- [ ] Write automigrations/codemods, if necessary
- [ ] Update documentation
- [x] Upgrade MDX in @storybook/docs-mdx
- [x] Deprecate/remove @storybook/mdx1-csf and @storybook/mdx2-csf packages
- [x] Refactor addon-docs to use mdx 3 compiler directly
```

**Comment by yannbf** [comment]
As additional information, here are the packages that relate to MDX:

- @storybook/docs-mdx ([upgrade PR here](https://github.com/storybookjs/docs-mdx/pull/13))
- @storybook/mdx1-csf 
- @storybook/mdx2-csf
- @storybook/addon-docs (via usage of the aforementioned mdx-csf packages)

According to @shilman we ideally should get rid of both mdx-csf packages, and bring their functionality directly into addon-docs. This means we will also stop supporting the CSF in MDX format.
