### ISSUE TITLE
Remove framework specific vite plugins

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#25210]
```[tasklist]
### Tasks
- [x] Remove @preact/preset-vite
- [x] Remove @vitejs/plugin-react
- [x] Remove @sveltejs/vite-plugin-svelte
- [x] Remove @vitejs/plugin-vue
```

**Comment by kasperpeulen** [comment]
Fixed in https://github.com/storybookjs/storybook/issues/25127
