### ISSUE TITLE
[Tracking]: Improve CLI versioning

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#25293]
This is a tracking issue to track the work on improving the CLI versioning, specifically making the `init`, `upgrade` and `sandbox` commands respect and use the version they are being invoked as.
```[tasklist]
### Milestone 1: `init` - Pairing
- [ ] https://github.com/storybookjs/storybook/issues/25501
- [ ] https://github.com/storybookjs/storybook/issues/25454
```

```[tasklist]
### Milestone 2: `upgrade` - Jeppe
- [x] Remove `--tag` and `--prerelease` flags
- [x] Remove usage of flags - including in sattelite repos like `test-runner`
- [x] Always upgrade to the version that the CLI is invoked as, instead of using the flags
- [x] Throw an error if trying to upgrade to a version that matches or is below the version already installed in the project
- [x] ~Optional: run `doctor` at the end of `upgrade`~
- [x] Detect existing version of `@storybook/cli` to avoid multiple versions detected
```

```[tasklist]
### Milestone 3: `sandbox` - Norbert
- [ ] https://github.com/storybookjs/storybook/issues/25559
- [x] Show a warning if `sandbox` is not invoked as either `latest` or `next`, as that is usually what the user wants
- [x] Handle `sandbox` with specific version
- [x] Remove usage of `--branch` flag - including in sattelite repos like `test-runner`
- [x] Bug: initiating happens in the CWD and not in the newly created sandbox directory, which it should
- [ ] https://github.com/storybookjs/storybook/issues/25603
```

```[tasklist]
### Milestone 4: Canary releases - Jeppe
- [x] Test that this works for canaries now
- [x] Add line to generated PR description like "To try out this canary run `npx storybook@<THE_CANARY_VERSION> sandbox`"
```

```[tasklist]
### Related Issue: Ensure these are fixed and close them - Jeppe
- [ ] https://github.com/storybookjs/storybook/issues/22214
```

```[tasklist]
### Milestone 5: Backport to 7.6
- [ ] https://github.com/storybookjs/storybook/issues/25521
- [ ] https://github.com/storybookjs/storybook/issues/25571
- [ ] https://github.com/storybookjs/storybook/issues/25572
- [ ] https://github.com/storybookjs/storybook/issues/25577
- [x] Release 7.6 patch
```
