### ISSUE TITLE
Find deprecations and remove them

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25331]
In Storybook 7, many APIs have been deprecated.  We should follow up and remove them in Storybook 8.

**ATTENTION: every change should contain its own PR alongside a migration note.**

```[tasklist]
### Tasks
- [ ] https://github.com/storybookjs/storybook/issues/25375
- [ ] https://github.com/storybookjs/storybook/issues/25373
- [ ] https://github.com/storybookjs/storybook/issues/25359
- [ ] https://github.com/storybookjs/storybook/issues/25345
- [ ] https://github.com/storybookjs/storybook/issues/25332
- [ ] https://github.com/storybookjs/storybook/issues/25346
- [ ] https://github.com/storybookjs/storybook/issues/25342
- [ ] https://github.com/storybookjs/storybook/issues/25369
- [ ] https://github.com/storybookjs/storybook/issues/25340
- [ ] https://github.com/storybookjs/storybook/issues/25362
- [ ] https://github.com/storybookjs/storybook/issues/25341
- [ ] https://github.com/storybookjs/storybook/issues/25343
- [ ] https://github.com/storybookjs/storybook/issues/25456
- [ ] https://github.com/storybookjs/storybook/issues/25338
- [ ] https://github.com/storybookjs/storybook/issues/25336
- [ ] https://github.com/storybookjs/storybook/issues/25337
- [ ] https://github.com/storybookjs/storybook/issues/25335
- [ ] https://github.com/storybookjs/storybook/issues/25339
- [ ] https://github.com/storybookjs/storybook/issues/25347
- [ ] https://github.com/storybookjs/storybook/issues/25344
- [ ] https://github.com/storybookjs/storybook/issues/25348
- [ ] https://github.com/storybookjs/storybook/issues/25366
- [ ] https://github.com/storybookjs/storybook/issues/25370
- [ ] https://github.com/storybookjs/storybook/issues/25368
- [ ] https://github.com/storybookjs/storybook/issues/25374
- [ ] https://github.com/storybookjs/storybook/issues/25372
- [ ] https://github.com/storybookjs/storybook/issues/25377
- [ ] https://github.com/storybookjs/storybook/issues/25361
- [ ] https://github.com/storybookjs/storybook/issues/25333
- [ ] https://github.com/storybookjs/storybook/issues/13545
- [ ] https://github.com/storybookjs/storybook/pull/24658
```

**Comment by valentinpalkovic** [comment]
@yannbf, @shilman Do we still support Flow? https://github.com/storybookjs/storybook/blob/next/code/lib/cli/README.md#L50-L52

I remember discussing in the past, and we concluded that parts of Storybook don't handle flow files at all (type extraction, for example,...)

**Comment by shilman** [comment]
@valentinpalkovic we don't really support flow. The story there is that there are still flow users out there and they contribute fixes to Storybook to get themselves unstuck. So "your mileage may vary". But we don't support flow explicitly.
