### ISSUE TITLE
[Tracking] 8.0 Automigrations

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#25432]
```[tasklist]
### Automigrations needed for 8.0
- [ ] https://github.com/storybookjs/storybook/issues/25429
- [ ] https://github.com/storybookjs/storybook/issues/25326
- [ ] https://github.com/storybookjs/storybook/issues/25430
- [ ] https://github.com/storybookjs/storybook/issues/25431
```
