### ISSUE TITLE
[Tracking]: Save from Controls 

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#26646]
This issue monitors and documents work on the "Save from Controls" feature, a mechanism for saving new stories from controls for existing story files and generating new story files from the manager UI.

Feature branch: https://github.com/storybookjs/storybook/tree/save-from-controls

```[tasklist]
### 0. Milestone: Preparations
- [ ] https://github.com/storybookjs/storybook/issues/26804
```

```[tasklist]
### 1. Milestone: Save from Controls
- [ ] https://github.com/storybookjs/storybook/issues/26657
- [ ] https://github.com/storybookjs/storybook/issues/26661
- [ ] https://github.com/storybookjs/storybook/issues/26861
```
```[tasklist]
### 2. Milestone: Trigger Generation of new Story files from the UI
- [ ] https://github.com/storybookjs/storybook/issues/26660
- [ ] https://github.com/storybookjs/storybook/issues/26658
- [ ] https://github.com/storybookjs/storybook/issues/26788
- [ ] https://github.com/storybookjs/storybook/issues/26840
- [ ] https://github.com/storybookjs/storybook/issues/26847
- [ ] Apply the final design
```

```[tasklist]
### Miscellaneous
- [ ] https://github.com/storybookjs/storybook/issues/26969
```
