### ISSUE TITLE
[Project SfC]: Tracking Ticket for Bugs

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#26969]
This issue will track bugs that are occurring while testing the new Save from Controls feature.
```[tasklist]
### Tasks
- [ ] https://github.com/storybookjs/storybook/issues/26970
- [ ] https://github.com/storybookjs/storybook/issues/26971
- [ ] https://github.com/storybookjs/storybook/issues/26972
- [ ] https://github.com/storybookjs/storybook/issues/26973
- [ ] https://github.com/storybookjs/storybook/issues/26974
- [ ] https://github.com/storybookjs/storybook/issues/26976
- [ ] https://github.com/storybookjs/storybook/issues/26977
```
