### ISSUE TITLE
[Tracking] Story globals

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#27210]
## RFC
https://github.com/storybookjs/storybook/discussions/23347

## Milestones

_Use this space to document how the project will be split up. At project kickoff, at minimum we should have all the milestones split up, and emphasize which is must-have and which is nice-to-have. As we dig in, flesh out the detailed implementational tasks in each milestone._ 

```[tasklist]
### Milestone 1:
- [ ] https://github.com/storybookjs/storybook/pull/27517
- [ ] https://github.com/ComponentDriven/csf/pull/95
- [ ] https://github.com/storybookjs/storybook/pull/26654
- [ ] https://github.com/storybookjs/storybook/pull/27705
- [x] Telemetry: Instrument the number of stories that use the story globals
```

```[tasklist]
### Milestone 2 - Addons:
- [ ] https://github.com/storybookjs/storybook/issues/27524
- [ ] https://github.com/storybookjs/storybook/issues/27523
- [ ] https://github.com/storybookjs/storybook/issues/27525
```

```[tasklist]
### Milestone 3 - After release:
- [ ] https://github.com/storybookjs/storybook/issues/28669
```

### Nice to Have

```[tasklist]
### Milestone 4 (Nice to have):
- [ ] ~~Automigration: Migrate viewport addon usage from parameters to global/globalTypes~~
- [ ] ~~Automigration: Migrate background addon usage from parameters to global/globalTypes~~
- [ ] ~~Automigration: Migrate themes addon usage from parameters to global/globalTypes~~
- [ ] https://github.com/storybookjs/storybook/issues/28784
- [ ] Revive https://github.com/storybookjs/storybook/pull/15231
- [ ] Update Chromatic Modes documentation
```

```[tasklist]
### Related issues that may be resolved by this project

```

## Decision Records

_Record here all the architectural decisions that we make along the way._

> ⏳ = pending decision
> ✅ = decision made and recorded
