### ISSUE TITLE
[Tracking] Allow play to mount the component of the story

### ISSUE THREAD

**Issue by kasperpeulen** [storybookjs/storybook#27390]
[[RFC] Allow play to mount the component of the story ](https://github.com/storybookjs/storybook/discussions/27389)
```[tasklist]
### Milestone 1: Allow play to mount the component of the story
- [x] Write RFC
- [x] Make sure to only skip mounting before play when mount is destructured in the play fn itself
- [x] Add mount property to the play function context which can be used to mount inside of the play function. (Accepting no argument and returning void)
- [x] Update CSF types and augment the return type of mount in the @storybook/test package
- [x] Make `@storybook/test` override mount (using a loader) to add a return element that is `within(canvasElement)`
- [x] Make sure `rendering` phase can be fired after `playing` phase (as overlapping phases)
- [x] **Test** Add stories test
- [ ] https://github.com/storybookjs/storybook/pull/27423
- [x] Make sure that (part of) testing-library API is accepted as argument of mount, when it easily maps to properties of the return type of render
- [x] Adjust portable stories play method to play the whole story, including loaders,beforeEach and render. It should accept an object with a mount property
- [ ] **Docs** Add new section to the play function docs, but don't update examples just yet
- [x] **Tests** (Story test for each renderer)
- [ ] Instrument mount so that it shows up in the interactions addon (Should have)
- [ ] Make sure docs runs serially (Nice to have)
- [ ] Make sure Docs are mounting properly as well (Out of scope)
```

```[tasklist]
### Milestone 2: BeforeAll hook
- [ ] Write RFC
- [ ] https://github.com/storybookjs/storybook/issues/28268
- [x] We can copy the API of vitest (including the cleanup function): https://vitest.dev/api/#beforeall
- [x] Make sure that beforeAll hook can run in portable stories somehow?
- [x] **Test**
- [ ] **Docs** The idea is that we recommend people to not write init code directly in preview.js anymore, but write this in beforeAll, because this would make our extract time much faster.
```

```[tasklist]
### Milestone 3 - Test runner research
- [ ] Write RFC for both a Vitest and Playwright-only based architecture and update the roadmap: https://github.com/orgs/storybookjs/projects/20/views/1
- [x] Spike Vitest test runner
- [x] Spike Playwright-only test runner
- [x] Analyze and write comparison report
- [ ] Nice to have: Spike vitest next plugin (Valentine)
```

**Comment by vanessayuenn** [comment]
Shipped in 8.2!
