### ISSUE TITLE
[Tracking]: Onboarding V2

### ISSUE THREAD

**Issue by cdedreuille** [storybookjs/storybook#28181]
### Design

- [ ] Design a new flow to introduce story generation and save from controls
- [ ] Improve the existing flow to avoid asking users to copy/paste code
- [ ] Create a prototype to encapsulate the changes
- [ ] Review the solution with key stakeholders

### Development

- [x] Replace welcome modal with new splash screen.
- [x] Update guided tour to include all the new steps.
- [x] Add a new modal at the end to show the newly created story.

### Stage 2 - Rethink onboarding holistically - Design + research only

- [ ] Improve configuration steps by introducing an in-app help centre.
- [ ] Explore having a sticky onboarding flow that anyone can visit even after the initial guided tour.
- [ ] Explore sign-in to Chromatic from the initial flow.

**Comment by vanessayuenn** [comment]
Shipped in 8.2!
