### ISSUE TITLE
[Tracking] Vitest integration

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#28388]
## RFC
https://github.com/storybookjs/storybook/discussions/28386

## Milestones

The Vitest integration effort is split into multiple types of work. It involves a Storybook plugin for Vitest, which transforms stories into tests (see RFC); Improvements in the core layer of Storybook; Some updates to the interactions addon and a creation of a new Storybook addon: `@storybook/addon-vitest`.

### Milestone 1 - Add filtering logic and improved UI to Storybook (extracted from VTA)

```[tasklist]
- [ ] https://github.com/storybookjs/storybook/issues/28682
- [ ] https://github.com/storybookjs/storybook/issues/28679
- [ ] https://github.com/storybookjs/storybook/issues/28680
- [ ] https://github.com/storybookjs/storybook/issues/28681
- [ ] https://github.com/storybookjs/storybook/issues/28683
```

### Milestone 2 - Portable stories and core improvements

```[tasklist]
- [ ] https://github.com/storybookjs/storybook/issues/28685
- [ ] https://github.com/storybookjs/storybook/pull/28764
- [ ] https://github.com/storybookjs/storybook/pull/28864
- [ ] https://github.com/storybookjs/storybook/pull/28829
- [ ] https://github.com/storybookjs/storybook/pull/28865
- [ ] https://github.com/storybookjs/storybook/pull/28825
- [x] metrics: https://github.com/storybookjs/storybook/pull/26764 [yann, michael]
```

### Milestone 3 - Experimental Vitest plugin - part 1
```[tasklist]
- [x] https://github.com/storybookjs/vitest-plugin/pull/1
- [x] https://github.com/storybookjs/vitest-plugin/pull/2
- [x] https://github.com/storybookjs/vite-plugin-storybook-nextjs/pull/3
- [ ] https://github.com/storybookjs/storybook/issues/28687
- [ ] https://github.com/storybookjs/storybook/issues/28707
- [ ] https://github.com/storybookjs/storybook/issues/28684
- [ ] https://github.com/storybookjs/storybook/issues/28744
- [ ] https://github.com/storybookjs/storybook/issues/28775
- [ ] https://github.com/storybookjs/storybook/issues/28777
- [ ] https://github.com/storybookjs/storybook/issues/28852
- [x] https://github.com/yannbf/mealdrop/pull/30
- [x] https://github.com/chromaui/chromatic/pull/8864
- [x] https://github.com/storybookjs/storybook-rsc-demo/pull/15
- [x] Use new `run` portable stories format (testingLibraryRender) [kasper, yann]
- [x] Write unit tests [yann]
- [x] Bug: Investigate double registration of plugin [yann]
- [x] Add unit testing/E2E testing/QA [kasper, yann]
- [x] metrics: make sure it's part of telemetry
```

### Milestone 4 - Experimental Vitest plugin - part 2
```[tasklist]
- [ ] https://github.com/storybookjs/storybook/issues/28807
- [ ] https://github.com/storybookjs/storybook/issues/28814
- [ ] https://github.com/storybookjs/storybook/issues/28889
- [ ] https://github.com/storybookjs/storybook/issues/28901
- [ ] https://github.com/storybookjs/storybook/issues/28903
- [ ] https://github.com/storybookjs/storybook/issues/28890
- [ ] https://github.com/storybookjs/storybook/issues/28904
- [ ] https://github.com/storybookjs/storybook/issues/28953
- [ ] **nice to have:** Research on isolation mode (workspace config)
- [ ] https://github.com/storybookjs/storybook/issues/28954
- [ ] https://github.com/storybookjs/storybook/issues/28930
```

### Milestone 5 - Documentation and content creation
```[tasklist]
- [ ] https://github.com/storybookjs/storybook/issues/28893
- [x] ViteConf: Prepare presentation [yann]
```

### Milestone 6 - Extended portable stories support
```[tasklist]
- [ ] https://github.com/storybookjs/storybook/issues/28895
- [ ] https://github.com/storybookjs/storybook/issues/28891
- [ ] https://github.com/storybookjs/storybook/issues/28892
- [ ] https://github.com/storybookjs/storybook/issues/28898
- [ ] https://github.com/storybookjs/storybook/issues/28897
- [ ] https://github.com/storybookjs/storybook/issues/28896
```

### Unplanned work

The following tasks were discussed to be out of scope, given the probable lack of time to work on them:

```[tasklist]
- [ ] https://github.com/storybookjs/storybook/issues/28688
- [ ] https://github.com/storybookjs/storybook/issues/28738
- [ ] https://github.com/storybookjs/storybook/issues/28686
- [ ] **Addon-interactions:** Improve error handling to allow non-playfn error logs [gert]
- [ ] **Vitest addon:** Panel with Vitest CLI raw logs [gert]
- [ ] **Vitest addon:** Pipe CLI output of Vitest onto Storybook's CLI
- [ ] **Vitest addon:** Implement Vitest orchestration layer [kasper, yann]
- [ ] **nice to have:** Move server connection checks to Storybook core [gert] https://github.com/storybookjs/storybook/issues/28258
- [ ] **nice to have:** Move top bar button (run tests) logic from VTA to Storybook [gert]
- [ ] **nice to have:** Remove/deprecate experimental topBar APIs in Storybook core [gert]
- [ ] **nice to have:** UI: Implement Superbar component
- [ ] **nice to have:** Implement afterEach as kind of a replacement for useEffect that is more compatible with test runner, as it can be await-ed. [kasper]
- [ ] **nice to have:** Audit all of our core addons and use the afterEach mechanism if applicable (and make PS compatible) [yann, kasper]
- [ ] **nice to have:** Implement a11y reporting mechanism [kasper]
- [ ] **nice to have:** Test package: Experiment with (inline) snapshots [kasper]
- [ ] Spike "always on watch mode" by running tests in watch mode via the CLI + watching for Junit files
```
