### ISSUE TITLE
[Tracking] Vite plugin for Next.js

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#28597]
## RFC
https://github.com/storybookjs/storybook/discussions/28428

## Milestones

_Use this space to document how the project will be split up. At project kickoff, at minimum we should have all the milestones split up, and emphasize which is must-have and which is nice-to-have. As we dig in, flesh out the detailed implementational tasks in each milestone._ 

```[tasklist]
### Milestone 1: Feature implementation
- [x] Feature: Support SWC transpiler
- [x] Feature: Support environment variables
- [x] Feature: Support various CSS technologies (Global CSS, CSS Modules, External Stylesheets, Tailwind CSS, Sass, CSS-in-JS)
- [x] Feature: next/link
- [x] Feature: next/image
- [x] Feature: next/font
- [x] Feature: next/head
- [x] Feature: next/cache
- [x] Feature: next/navigation
- [x] Feature: next/router
- [x] Feature: RSC
- [x] Mocks: Storybook mocks for Next.js API's
```

```[tasklist]
### Milestone 2: Releasing and Documentation
- [x] Testing: Ensure it works in vitest with portable stories
- [x] Setup CI and Chromatic on example project
- [x] Publish vite-plugin-storybook-nextjs
- [ ] https://github.com/storybookjs/storybook/issues/28789
- [x] Documentation
- [x] Blog post
```

### Nice to Have

```[tasklist]
### Milestone 3 (Stretch goals)
- [ ] https://github.com/storybookjs/storybook/issues/28799
- [ ] Feature: Fast-refresh
- [ ] Ensure Windows compatibility
```

```[tasklist]
### Related issues that may be resolved by this project
- [x] next/dynamic does not work
- [ ] Refresh bug on startup
- [x] "Could not find default container" when "waitFor" is used
- [ ] [Bug] Chromatic: Invalid hook call
```

## Decision Records

_Record here all the architectural decisions that we make along the way._

> ⏳ = pending decision
> ✅ = decision made and recorded
