### ISSUE TITLE
[Tracking]: Unified UI Testing 🔮

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#29088]
## 🧑‍🤝‍🧑 Who: @ghengeveld, @yannbf and @valentinpalkovic 

This is a tracking issue the Unified UI Testing 🔮 project. The purpose of this issue is to keep tracking of the overall status of the project and tasks, and plan everything around it.

# ⚠️ Problem

Storybook has the potential to be the go-to tool for comprehensive UI testing, unifying both the existing Visual Regression Testing (VRT) and Component Testing (CT) experiences. However, the current implementation falls short in two key areas:

**1️⃣ Fragmented workflow**

As of 8.3, users begin their Storybook CT experience with Vitest via the CLI, then transition into Storybook for visual debugging. More specifically, this process includes:

1. Configuring the `storybookScript` option in the Vitest plugin.
2. Running `vitest` in watch mode from the CLI, which spawns Storybook in the background.
3. Viewing test failure outputs in the CLI and clicking a link to open Storybook for visual debugging.

This workflow centers on Vitest, making Storybook feel like a "sidekick" (albeit a powerful one). The constant switching between Vitest and Storybook disrupts the development flow and makes the process feel fragmented.

**2️⃣ Incoherent design and under-utilized CT experience**

Storybook already provides a powerful VRT experience via Visual Test Addon. We have an opportunity to create a more coherent and optimized experience that fully leverages both VRT and CT capabilities within Storybook.

# 🏁 Goals

The high-level goals of this project are:

- Introduce a way to trigger test runs from the Storybook Manager UI.
- Support both the Storybook Test addon (Vitest) and the Visual Test addon (Chromatic).
- Support scoping down to groups, components and stories (when supported by the test provider).
- Update (aggregate) story status indicators on groups, components and stories with new icons.

# 🚩 Milestones

```[tasklist]
## 1. Testing module essentials
- [ ] https://github.com/storybookjs/storybook/issues/29092
- [ ] https://github.com/storybookjs/storybook/issues/29093
- [ ] https://github.com/storybookjs/storybook/issues/29094
- [ ] https://github.com/storybookjs/storybook/issues/29095
- [ ] https://github.com/storybookjs/storybook/issues/29096
- [ ] https://github.com/storybookjs/storybook/issues/29214
- [ ] https://github.com/storybookjs/storybook/issues/29215
- [ ] https://github.com/storybookjs/storybook/issues/29213
- [x] Update Notifications UI to not overlap Testing Module
- [ ] https://github.com/storybookjs/storybook/issues/29262
- [ ] https://github.com/storybookjs/storybook/issues/29289
- [ ] Clear story statuses on Storybook session over
- [ ] Uninstall addon-interactions on sb add addon-test
- [x] Update sandboxes to use addon-test rather than addon-interactions
```

```[tasklist]
## 2. Discrepancy handling
- [ ] https://github.com/storybookjs/storybook/issues/29162
- [ ] https://github.com/storybookjs/storybook/issues/29312
- [ ] https://github.com/storybookjs/storybook/issues/29216
- [ ] https://github.com/storybookjs/storybook/issues/29120
- [ ] https://github.com/storybookjs/storybook/issues/29349
```

```[tasklist]
## 3. Updating VTA
- [ ] https://github.com/storybookjs/storybook/issues/29097
- [ ] https://github.com/storybookjs/storybook/issues/29098
```

```[tasklist]
## 4. Static builds
- [ ] https://github.com/storybookjs/storybook/issues/29165
- [ ] Disable expandability of the testing module
```

```[tasklist]
## 5. Watch mode
- [x] Support `watchable` property for test providers
- [x] Render an "eye" toggle button which emits a `_WATCH` event
- [x] Handle watch event in Storybook Test addon
```

```[tasklist]
## 6. Run individual stories
- [ ] https://github.com/storybookjs/storybook/issues/29108
- [ ] https://github.com/storybookjs/storybook/issues/29107
- [ ] https://github.com/storybookjs/storybook/issues/29101
- [ ] “Run component tests” action (Channel API)
```

```[tasklist]
## 7. Enhanced story status
- [ ] Add support for a `count` property (shown on the right in the dropdown)
- [ ] Aggregate (sum) these counts on groups and components
```

```[tasklist]
## 8. Portable stories fixes
- [ ] https://github.com/storybookjs/storybook/issues/29324
- [ ] Add Storybook hooks support in portable stories
- [ ] https://github.com/storybookjs/storybook/issues/29244
```

# Out of scope

- Integrating with A11y addon
- Support for code coverage reporting

# Follow-up work

- Setup a sandbox to use (and test) addon-interactions
