### ISSUE TITLE
[Tracking]: Focused Tests 🎯

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#29529]
## 🧑‍🤝‍🧑 Who: @JReinhold, @ndelangen and @ghengeveld 

This is a tracking issue for the Focused Tests 🎯 project. The purpose of this issue is to keep tracking of the overall status of the project and tasks, and plan everything around it. This project is a continuation of #29088 and is related to #29530 and #29531.

# ⚠️ Problem

The new Testing Module is great for running tests across all stories in the whole project, however often you are only working on a subset of stories or components, and therefore you only need to run a specific set of tests. Only running a subset of tests will be faster than running all tests all the time.

# 🏁 Goals

1. Users can run tests at the story, component, or directory level.
2. Other test providers/addons (eg. a11y) are also able to leverage this via a new Story Actions API

# 🚩 Milestones

```[tasklist]
## Run individual stories
- [x] we need to discuss if we're doing sibling UI or child checkboxes, and we need to figure that out fast
- [ ] https://github.com/storybookjs/storybook/issues/29107
- [ ] https://github.com/storybookjs/storybook/issues/29101
- [ ] https://github.com/storybookjs/storybook/issues/29540
```

```[tasklist]
## Nice-to-haves
- [ ] https://github.com/storybookjs/storybook/issues/29541
```
