### ISSUE TITLE
[Tracking]: Project Coverage 🛡️

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#29530]
## 🧑‍🤝‍🧑 Who: @JReinhold, @ndelangen and @ghengeveld 

This is a tracking issue for the Project Coverage 🛡️ project. The purpose of this issue is to keep tracking of the overall status of the project and tasks, and plan everything around it. This project is a continuation of #29088 and is related to #29529 and #29531.

# ⚠️ Problem

It's not immediately clear how much of a project's UI is covered by tests/stories. Storybook can provide that via Vitest's coverage report.

# 🏁 Goals

1. Users are able to view _project coverage_ in Storybook.

	1. User should be able to view project test coverage % inside storybook. The coverage % should update every time user does a complete test runs.
	2. User should also be able to view the overall project coverage percentage within storybook, and clicking on the coverage takes you to the Vitest coverage report. 
	3. Project coverage should respect the Vitest coverage config. 
4. Document how to use this and integrate with coverage tools, CodeCov, etc.
 
![Image](https://github.com/user-attachments/assets/786edbbe-d5b3-4326-9438-d06c24f7867a)

# 🚩 Milestones

```[tasklist]
## Main milestone
- [x] Add extensions UI to Component Tests Testing Module - edit mode only
- [x] Enable coverage in Vitest runs when coverage event is sent
- [x] Respect user's coverage config in their Vitest config
- [x] Display coverage  percentage in Testing Module UI
- [x] Make Vitest's HTML-based coverage report available on the server, so it can be linked from the manager
- [ ] What about nycrc?
- [x] Set circle color from configured coverage thresholds/watermarks
- [x] Make Testing Module UI compatible with dynamical render heights
- [ ] https://github.com/storybookjs/storybook/issues/29613
- [ ] https://github.com/storybookjs/storybook/issues/29721
```
