### ISSUE TITLE
[Tracking]: Component Testing Enhancements 🔧

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#29531]
## 🧑‍🤝‍🧑 Who: @JReinhold, @ndelangen and @ghengeveld 

This is a tracking issue for the Component Testing Enhancements 🔧 project. The purpose of this issue is to keep tracking of the overall status of the project and tasks, and plan everything around it. This project is a continuation of #29088 and is related to #29529 and #29530.

# ⚠️ Problem

There was a few unresolved items in #29088 that we want to work on to improve the Component Testing experience. Further more, we're continuously receiving feedback on the new feature that we want to address.

# Tasks

```[tasklist]
#### Must Haves
- [ ] https://github.com/storybookjs/storybook/issues/29745
- [ ] https://github.com/storybookjs/storybook/issues/29796
- [ ] https://github.com/storybookjs/storybook/issues/29797
- [ ] https://github.com/storybookjs/storybook/issues/29613
- [ ] #29771
- [ ] #29772
- [ ] #29775
- [ ] #29776
- [ ] #29778
- [ ] #29779
- [ ] https://github.com/storybookjs/storybook/issues/29686
- [ ] https://github.com/storybookjs/addon-svelte-csf/issues/213
- [ ] ~https://github.com/storybookjs/storybook/issues/26842~
- [ ] https://github.com/storybookjs/storybook/issues/29703
- [ ] https://github.com/storybookjs/storybook/issues/29784
- [ ] https://github.com/storybookjs/storybook/issues/29349
- [ ] https://github.com/storybookjs/storybook/issues/29647
- [ ] https://github.com/storybookjs/storybook/issues/28890
- [ ] https://github.com/storybookjs/storybook/issues/29652
- [ ] https://github.com/storybookjs/storybook/issues/29785
- [ ] https://github.com/storybookjs/storybook/issues/29741
- [ ] https://github.com/storybookjs/storybook/issues/29742
- [ ] https://github.com/storybookjs/storybook/issues/29650
- [ ] https://github.com/storybookjs/storybook/issues/29767
- [ ] https://github.com/storybookjs/storybook/issues/29794
- [ ] https://github.com/storybookjs/storybook/issues/29799
- [ ] https://github.com/storybookjs/storybook/issues/30009
```

```[tasklist]
### Expandable Scope
- [ ] https://github.com/storybookjs/storybook/issues/29653
- [ ] https://github.com/storybookjs/storybook/issues/25073
- [ ] https://github.com/storybookjs/storybook/issues/29651
- [ ] https://github.com/storybookjs/storybook/issues/29572
- [ ] https://github.com/storybookjs/storybook/issues/29602
- [ ] #29773
- [ ] #29774
- [ ] #29780
- [ ] #29781
- [ ] #29782
- [ ] https://github.com/storybookjs/storybook/issues/29567
- [ ] https://github.com/storybookjs/storybook/issues/29575
- [ ] #29777
- [ ] #29783
```

```[tasklist]
### Needs Triage
- [ ] https://github.com/storybookjs/storybook/issues/29812
- [ ] https://github.com/storybookjs/storybook/issues/28954
- [ ] https://github.com/storybookjs/storybook/issues/28896
- [ ] https://github.com/storybookjs/storybook/issues/28898
- [ ] https://github.com/storybookjs/storybook/issues/28891
- [ ] https://github.com/storybookjs/storybook/issues/28897
- [ ] Add Storybook to the [Vitest Ecosystem CI](https://github.com/vitest-dev/vitest-ecosystem-ci)
- [ ] Tech debt: Combine `TestManager` and `VitestManager`
- [ ] https://github.com/storybookjs/storybook/issues/30010
- [ ] https://github.com/storybookjs/storybook/issues/30011
- [ ] https://github.com/storybookjs/storybook/issues/30028
- [ ] https://github.com/storybookjs/storybook/issues/30048
- [ ] https://github.com/storybookjs/storybook/issues/30053
- [ ] https://github.com/storybookjs/storybook/issues/30087
```
