### ISSUE TITLE
Addon-docs: Meta block for component metadata

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#6933]
Clean up the component metadata declaration and also its "compiled" output in the MDX loader.
- [x] Add a new doc block called Meta
- [x] Update compiler to export Meta contents as componentMeta
- [x] Update the modules format loader to use default instead of componentMeta
- [x] Update compiler to export Meta contents as default
- [x] Update compiler to export the MDX as a field on default
- [x] Update source loader to use default instead of componentMeta
- [ ] FUTURE: update doc blocks to not "need" storybook

WHY:
- Want the component format to use export default for metadata
- Want the MDX compilation to be drop-in compatible with other MDX systems (if you remove the Storybook Loader)

### Input

```md
import { Story } from '@storybook/addon-docs/blocks';

export componentMeta = { title: 'Foo', ... };

## Some MDX here

<Story name="bar"> ... </Story>
```

### Output

```js
import { Story } ...
export componentMeta = { title: 'Foo' }
export const bar = () => ...
export default class MDXComponent { /* mdx etc. here */ }
```

### Input

```md
import { Meta, Story } from '@storybook/addon-docs/blocks';

<Meta title="Foo" />

## Some MDX here

<Story name="bar"> ... </Story>
```

### Output

```js
import { Meta, Story } ...
const componentMeta = { title: 'Foo' ... }
export default meta;
export const bar => ...
meta.Docs = class MDXContent { /* mdx etc. here */ }
```
