### ISSUE TITLE
Addon-docs: Review and merge 

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#7101]
[SB Docs](https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a) is a big new Storybook feature that has been developed and released as `5.2.0-alpha.x` from the https://github.com/storybookjs/storybook/tree/release/docs-technical-preview branch.

Now we're in a tricky situation where we need to get this work merged back into `next`. Rather than a single giant merge, I'm going to break the work into a series of small PRs that can be properly reviewed and refined. This umbrella issue tracks that work.

## Addon PRs

- [x] Refactor story_store #6382
- [x] Support multiple viewMode tabs in UI #7107
- [x] Module story format + framework parameter #7110
- [x] Source loader #7117
- [x] DocsPage & doc blocks #7119
- [x] MDX loader & docs preset #7145 
- [x] `--docs` documentation-only view #7154 
- [x] Component param codemod #7155
- [x] Module format codemod #7174

## Example PRs

- [x] angular-cli #7257 
- [ ] ember-cli
- [x] html-kitchen-sink #7454 
- [ ] marko-cli
- [ ] mithril-kitchen-sink
- [x] official-storybook #7145 
- [ ] polymer-cli
- [ ] preact-kitchen-sink
- [ ] rax-kitchen-sink
- [ ] riot-kitchen-sink
- [x] svelte-kitchen-sink
- [x] vue-kitchen-sink #7222

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.29 containing PR #6382 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@debug` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.29 containing PR #6382 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@debug` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.30 containing PR #7171 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by damusix** [comment]
Hey @shilman, not sure if you are aware, but currently Riot has been upgraded to version 4, and it is not compatible with Riot 3. Lot of the dependencies currently in Storybook/Riot will not work with Riot 4. If you'd like to see an example of Riot4 with webpack, I have one [in my boilerplate project](https://github.com/damusix/riot-4-boilerplate/blob/master/webpack.config.js). Check out how [the dependencies are now different](https://github.com/damusix/riot-4-boilerplate/blob/master/package.json).

I really like story book and I really like Riot. Would love to see them work together. Also, if there's anything I can do to help, feel free to ask!

**Comment by shilman** [comment]
@damusix Please open a separate issue about Riot4 support. Hopefully someone will pick it up!

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.32 containing PR #7175 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.34 containing PR #7222 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.0 containing PR #7418 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.2 containing PR #7454 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by envision** [comment]
I don't think Vue kitchen sink example is done yet because there is no TypeScript configured in that example.

With Vue 3.0 approaching, people should already be using TypeScript in their Vue projects, and it seems this not straightforward setup to configure when using addon-docs, ref https://github.com/storybookjs/storybook/issues/8082

**Comment by envision** [comment]
In addition, please note that by default Vue projects are configured to use '@' as an Webpack alias to point to */src* folder, so this should be configured as well.

**Comment by shilman** [comment]
@envision would you mind filing a separate issue containing Vue improvements you'd like to see? I'm working with @Aaron-Pool and @elevatebart to get official Vue support ready in 5.3. This issue is just about getting the alpha merged, which is done

**Comment by shilman** [comment]
@envision #8082 seems like a good place to aggregate this

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.23 containing PR #7668 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Closing this and will follow up with individual issues as needed

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.26 containing PR #7673 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
