### ISSUE TITLE
Module format: Make story decorators first-class

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#7486]
Module format decorator syntax should parallel parameter syntax. The only reason it didn't is because we didn't want to add more fields to the `storiesOf.add` API.

## Breaking change

This was an oversight in the first implementation of modules format, and so this deprecation will be a breaking change for anybody who used the module format in alpha. But it's not a hard breaking change, just a deprecation warning. And better to make the move before final release.

## Current

```js
export const bar = () => <.../>
bar.story = {
  name: 'bar bar',
  parameters: { ..., decorators: [...] }
}
```

## Proposed

```js
export const bar = () => <.../>
bar.story = {
  name: 'bar bar',
  parameters: { ... },
  decorators: [...]
}
```

## Todo

- [x] Update `load` to support story decorators
  - [x] Warn on old-style usage
- [x] Update `codemods`
  - [x] storiesof-to-module
  - [x] module-to-mdx
  - [x] mdx-to-module
- [x] Update MDX compiler & docs & examples

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.4 containing PR #7490 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
