### ISSUE TITLE
Module / MDX format: Make `component` a top-level construct

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#7522]
Currently, users specify components using parameters. Let's make it a first class feature since components are central to Storybook.

## Before

Module:

```js
export default {
  title: 'path|to/Button',
  parameters: { component: Button }
}
```

MDX:

```js
<Meta title="path|to/Button" parameters={{ component: Button }} />
```

## After

Module:

```js
export default { title: 'path|to/Button', component: Button }
```

MDX:

```js
<Meta title="path|to/Button" component={Button} />
```

**NOTE:** The `component` will still appear as a parameter. But it may be expected at the top-level by some tools in the future.

## To-do

- [ ] Update loader
- [ ] Update MDX compiler
- [ ] Update documentation / examples
- [ ] Update add-component codemod

**Comment by ndelangen** [comment]
makes sense

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.6 containing PR #7524 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
