### ISSUE TITLE
UI: Tab selection / enablement

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#8631]
The release of [Storybook Docs](https://medium.com/storybookjs/storybook-docspage-e185bc3622bf) has opened up a variety of related UI issues around tab management & selection. This is an umbrella issue to organize a set of related feature requests:

- [ ] Select tab based on story #8630 
- [ ] Hide canvas tab #7066
- [ ] Reorder canvas/docs tab https://github.com/storybookjs/storybook/issues/7066#issuecomment-524296135

In addition I've heard:
- [ ] Disable docs tab for a story
- [ ] Rename canvas tab

**Comment by chenkaza** [comment]
Can you please add :
-  changing the canvas tab name/title. (in my case it's 'Playground' but I don't think it matters).

**Comment by EdenTurgeman** [comment]
Please make this a reality, A lot of people seem to want this.

**Comment by mikrotron** [comment]
These are great ideas to make the Docs more flexible!  What I am specifically interested in, and haven't found a workaround for yet, is for a pure MDX story to _not_ automatically switch to the Docs tab.  For example, opening this story:

https://storybookjs-next.now.sh/official-storybook/?path=/docs/addons-docs-docs-only--page

Will switch from the Canvas tab to the Docs tab, and then when clicking other stories, the user remains on the Docs tab. Since they didn't click that tab explicitly, it is disorienting.  In fact, I'd like to hide that whole ToolBar to simplify the UI for our Storybook, but because of this behaviour that would be even more confusing for users.

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.2 containing PR #9095 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
