### ISSUE TITLE
Improvements to MDX linking for 6.0

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#9330]
The basics of MDX linking have been released with 5.3.

It works "fine" but there are a few improvements that should land in 6.0:

- [x] Improve external links detection: https://github.com/storybookjs/storybook/issues/9302
- [x] Use SB select story API https://github.com/storybookjs/storybook/issues/9328
- [ ] Replace remark-slug plugin https://github.com/storybookjs/storybook/issues/9329

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
